version: "3"
services:
  reverseproxy:
      image: khaleeed/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: khaleeed/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: udagrammsdb
      POSTGRESS_PASSWORD: udagrammsdb 
      POSTGRESS_DB: udagrammsdb 
      POSTGRESS_HOST: udagrammsdb.czsj8umx3swo.us-east-1.rds.amazonaws.com 
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_BUCKET: udagrammsbt
      JWT_SECRET: helloWorld
      URL: "http://localhost:8100"
  backend-feed:
    image: khaleeed/udacity-restapi-feed
    volumes: 
     - $HOME\.aws
    environment:
      POSTGRESS_USERNAME: udagrammsdb
      POSTGRESS_PASSWORD: udagrammsdb 
      POSTGRESS_DB: udagrammsdb 
      POSTGRESS_HOST: udagrammsdb.czsj8umx3swo.us-east-1.rds.amazonaws.com 
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_BUCKET: udagrammsbt
      JWT_SECRET: helloWorld
      URL: "http://localhost:8100"
  frontend:
    image: khaleeed/udacity-frontend:local
    ports:
      - "8100:80"
